<div class="container2">
  
    <div class="main1">
      <div class="titleh1">
        <b></b>
        <span><a href="{dede:field name='typeurl' /}">{dede:field name='typename'/}<br />{dede:field name='typename1'/}</a></span>
        <b></b>
      </div> 
      <div class="content1">
        {dede:field name='content' function="htmlspecialchars(cn_substr(Html2text(@me),450))"/}...
      </div>
        
    </div>
    
  </div>