
<field:casetitle itemname="案例名称" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:casetitle>

<field:caseimg itemname="图片" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:caseimg>


<field:casecontent itemname="案例介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="2500" page="">
</field:casecontent>
