<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">	
</field:body>	

<field:fundsize itemname="基金规模" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:fundsize>

<field:income itemname="预期年化收益" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:income>

<field:progress itemname="募集进度" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:progress>

<field:distribution itemname="收益分配方式" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:distribution>

<field:bank itemname="托管银行" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:bank>

<field:origin itemname="认购起点（万）" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:origin>

<field:yield itemname="收益率（100-300万）" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:yield>
