成立于2009年，是一家集资产收购与整合、房地产营销策划、销售代理、风险投资为一体的综合型投资管理公司。公司资金实力雄厚，投资经验丰富。自成立以来，在深圳市成功投资收购了民生银行大厦、荔馨国际公寓、老街新寓、后海小院、浪漫满屋、博客公寓、田贝综合楼、粤海新村及龙城华府等项目。公司通过对上述房地产项目的收购、整合，二次改造包装策划后将该项目打包或拆分销售，已完成了荔馨国际公寓、老街新寓、后海小院、浪漫满屋、博客公寓等项目的全部改造销售。
 <div class="case">
      <!-- <ul class="ib2_nav fr">
        <li class="fl on">所有案例</li>
        <li class="fl">不动产基金</li>
        <li class="fl">文化基金</li>
        <li class="fl">产业基金</li>
      </ul> -->
      <div class="ib2_move">
        <div class="ib2_list_box">
          <ul class="ib2_list clearfix" style="display: block;">
          {dede:arclist  titlelen='35' typeid='34' limit='0,15'}
            <li class="fl">
              <a href="[field:arcurl/]">
                <div class="top">
                  <img src="[field:litpic/]" width="260px" height="214px">
                </div>
                <div class="bottom">
                  <h2>[field:title/]</h2>
                 
                </div>
              </a>
            </li>
           {/dede:arclist}                                           
          </ul>
        </div>
      </div>   
      <div class="slide_btn">
        <a href="#" class="left_btn" id="idx_left_btn"></a>
        <a href="#" class="right_btn" id="idx_right_btn"></a>
      </div>
    </div>
  </div>