<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'></a>\"); ",5,131);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",144,161);
$z[2]=Array("arcurl","",176,191);
$z[3]=Array("title","",207,221);
$z[4]=Array("pubdate","",270,316);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",341,355);
$z[6]=Array("scores","",380,395);
$z[7]=Array("description","",430,450);

?>