<ul class='newsul'> 
成立于2009年，是一家集资产收购与整合、房地产营销策划、销售代理、风险投资为一体的综合型投资管理公司。公司资金实力雄厚，投资经验丰富。自成立以来，在深圳市成功投资收购了民生银行大厦、荔馨国际公寓、老街新寓、后海小院、浪漫满屋、博客公寓、田贝综合楼、粤海新村及龙城华府等项目。公司通过对上述房地产项目的收购、整合，二次改造包装策划后将该项目打包或拆分销售，已完成了荔馨国际公寓、老街新寓、后海小院、浪漫满屋、博客公寓等项目的全部改造销售。
  <li>
    <img src="[field:litpic /]" alt="[field:title /]">
    <div class="aboutnews">
      <div class="top">
        <div class="title"><a href="[field:arcurl /]">[field:title /]</a></div>
        <div class="date">
          20[field:pubdate function="MyDate('y-m-d',@me)"/]
        </div>
      </div>
      <p>[field:description function='cn_substr(@me,230)' /]...</p>
        <a href="[field:arcurl /]">详情&nbsp;&gt;&nbsp;&gt;</a>
    </div>
  </li>
</ul>