<ul class='newsul'> 
<li>
<img src="[field:litpic /]" alt="[field:title /]">
<div class="aboutnews">
            <div class="top">
            <div class="title">[field:title /]</div>
            <div class="date">([field:pubdate function="MyDate('y-m-d',@me)"/])</div></div>
            <p>[field:keywords /]</p>
            <a href="[field:arcurl /]">详情&nbsp;&gt;&nbsp;&gt;</a>
          </div>
</li>

</ul>