<?php
$z[0]=Array("array","\r\n                    global \$dsql;\r\n                    @me =@me['id'];\r\n                    \$sql = \"select * from #@__arctype where id=11\";    /*顶级栏目id\r\n                    \$dsql->Execute('a',\$sql);\r\n                    \$one = \$dsql->GetArray('a');\r\n                    @me =substr(Html2Text(\$one['content']),0,660);\r\n                    ",22,410);
$z[0][4]['runphp']="yes";

?>