<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">	
</field:body>	
<field:fundsize itemname="基金规模" autofield="1" notsend="0" type="int" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fundsize>
<field:deadline itemname="期限" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:deadline>
<field:income itemname="预期年化收益" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:income>
<field:progress itemname="募集进度%" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:progress>
<field:distribution itemname="收益分配方式" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:distribution>
<field:bank itemname="托管银行" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:bank>
<field:manager01 itemname="基金管理人" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:manager01>
<field:origin itemname="认购起点（万）" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:origin>
<field:information itemname="基本资料" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="25000" page="">
</field:information>
<field:measure itemname="产品亮点" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:measure>
<field:repayment itemname="还款来源" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:repayment>
<field:collectprogress itemname="募集进度" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="600" page="">
</field:collectprogress>

<field:establish itemname="成立进度" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="600" page="">
</field:establish>

<field:projectProgress itemname="项目进度" autofield="1" notsend="0" type="textdata" isnull="true" islist="0" default=""  maxlength="600" page="">
</field:projectProgress>
<field:exitprogress itemname="退出进度" autofield="1" notsend="0" type="textdata" isnull="true" islist="0" default=""  maxlength="600" page="">
</field:exitprogress>
<field:state itemname="状态" autofield="1" notsend="0" type="radio" isnull="true" islist="1" default="正在募集,存续期,已兑付"  maxlength="250" page="">
</field:state>