<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">	
</field:body>	

<field:fundsize itemname="基金规模" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:fundsize>

<field:income itemname="预期年化收益" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:income>
