<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/160506/1-160506162U3.jpg ",93,239);
$z[1][4]['ddimg']="/uploads/allimg/160506/1-160506162U3.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1920";
$z[1][4]['height']="500";
$z[2]=Array("img"," /uploads/allimg/160506/1-160506162918.jpg ",241,389);
$z[2][4]['ddimg']="/uploads/allimg/160506/1-160506162918.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1920";
$z[2][4]['height']="500";
$z[3]=Array("img"," /uploads/allimg/160506/1-160506162918-50.jpg ",391,545);
$z[3][4]['ddimg']="/uploads/allimg/160506/1-160506162918-50.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1920";
$z[3][4]['height']="500";

?>