<ul class='newsul'> 
  <li>
    <img src="[field:litpic /]" alt="[field:title /]">
    <div class="aboutnews">
      <div class="top">
        <div class="title"><a href="[field:arcurl /]">[field:title /]</a></div>
        <div class="date">
          20[field:pubdate function="MyDate('y-m-d',@me)"/]
        </div>
      </div>
      <p>[field:description function='cn_substr(@me,210)' /]...</p>
        <a href="[field:arcurl /]">详情&nbsp;&gt;&nbsp;&gt;</a>
    </div>
  </li>
</ul>