<li class="fl">
              <a href="[field:arcurl/]">
                <div class="top">
                  <img src="[field:litpic/]">
                </div>
                <div class="bottom">
                  <h2>[field:title/]</h2>
                  <p>[field:description]</p>
                </div>
              </a>
            </li>
           
           
           
                                                     
          </ul>
          <ul class="ib2_list clearfix">
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
          </ul>
           <ul class="ib2_list clearfix">
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
          </ul>
           <ul class="ib2_list clearfix">
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
            <li class="fl">
              <a href="#">
                <div class="top">
                  <img src="{dede:global.cfg_templets_skin/}/images/img-2.jpg">
                </div>
                <div class="bottom">
                  <h2>留学生创业大厦二期</h2>
                  <p>深圳南山区高新科技术产业园南区</p>
                </div>
              </a>
            </li>
          </ul>
        </div>
      </div>
     
    <div class="slide_btn">
                    <a href="#" class="left_btn" id="idx_left_btn"></a>
                    <a href="#" class="right_btn" id="idx_right_btn"></a>
                </div>

    </div>
  </div> 
  <div class="container">
    <div class="titleh1">
        <b></b>
        <span>新闻资讯<br />News Information</span>
        <b></b>
    </div>
    <div class="news">
      <ul class="newscontent">
        <li>
          <p class="em13">行业动态<br />Vocation News</p>
          <div class="newshot">
          {dede:arclist typeid='25' titlelen='50' limit='0,1'}
            <img src="[field:litpic/]">
            <div class="head">[field:pubdate function="MyDate('Y',@me)" /]<br />[field:pubdate function="MyDate('m.d',@me)" /]</div>
            <p class="title">[field:title/]</p>
            <div class="text" id="news1">[field:description/]</div>
            <a class="more" href="/plus/list.php?tid=25">MORE</a>