<?php
$z[0]=Array("global","",60,92);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("field","",100,129);
$z[1][4]['name']="typename";
$z[2]=Array("field","",174,203);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",225,254);
$z[3][4]['name']="typename";
$z[4]=Array("field","",330,359);
$z[4][4]['name']="typename";
$z[5]=Array("field","",379,466);
$z[5][4]['name']="content";
$z[5][4]['function']="htmlspecialchars(cn_substr(Html2text(@me),350))";
$z[6]=Array("field","",494,523);
$z[6][4]['name']="typeurl";

?>