<?php
$z[0]=Array("field","",9,37);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",39,68);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n<li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n",76,187);
$z[2][4]['type']="son";
$z[2][4]['row']="8";
$z[3]=Array("arclist"," <ul class='autod'> \r\n<li><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n<li>([field:pubdate function=\"MyDate('m-d',@me)\"/])</li>\r\n</ul>\r\n",189,385);
$z[3][4]['titlelen']="42";
$z[3][4]['row']="10";

?>