<?php
$z[0]=Array("channelartlist"," \r\n      <ul class=\"footer_left\">\r\n      	    <h2>{dede:field name='typename'/}</h2>\r\n      	    {dede:channel type='son'}\r\n      		<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n      		{/dede:channel}\r\n      </ul>\r\n      ",87,386);
$z[0][4]['typeid']="top";
$z[0][4]['row']="4";
$z[1]=Array("global","",749,775);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",826,850);
$z[2][4]['name']="cfg_beian";

?>