<?php
$z[0]=Array("global","",107,139);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",163,189);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",871,896);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("channelartlist"," \r\n            <li><a href='{dede:field name='typedir'/}'>{dede:field name='typename'/}</a>\r\n            <dl class=\"spe\">\r\n            {dede:channel type='son' noself='true'} \r\n         <dd><a href='[field:typeurl/]'>[field:typename/]</a></dd>{/dede:channel}\r\n            </dl></li>",1557,1965);
$z[3][4]['typeid']="top";
$z[3][4]['currentstyle']="<li class=hover><a href=~typelink~>~typename~</a></li>";

?>