<?php
$z[0]=Array("field","",143,162);
$z[0][4]['name']="title";
$z[1]=Array("global","",163,189);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",230,259);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",299,357);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",375,407);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",491,523);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",625,660);
$z[6][4]['filename']="head.htm";
$z[7]=Array("global","",714,746);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("field","",754,813);
$z[8][4]['name']="typeid";
$z[8][4]['function']="GetTopTypename(@me)";
$z[9]=Array("field","",954,983);
$z[9][4]['name']="position";
$z[10]=Array("field","",1064,1123);
$z[10][4]['name']="typeid";
$z[10][4]['function']="GetTopTypename(@me)";
$z[11]=Array("channel","\r\n      <li>\r\n        <a href='[field:typeurl/]'>[field:typename/]</a>\r\n      </li>",1140,1337);
$z[11][4]['type']="son";
$z[11][4]['currentstyle']="<li class='hover'><a href='~typelink~'>~typename~</a></li>";
$z[12]=Array("field","",1418,1439);
$z[12][4]['name']="content";
$z[13]=Array("include","",1496,1533);
$z[13][4]['filename']="footer.htm";

?>