<?php
$z[0]=Array("field","",143,162);
$z[0][4]['name']="title";
$z[1]=Array("global","",163,189);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",230,259);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",299,357);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",375,407);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",491,523);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",605,637);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("include","",705,740);
$z[7][4]['filename']="head.htm";
$z[8]=Array("global","",794,826);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("field","",834,893);
$z[9][4]['name']="typeid";
$z[9][4]['function']="GetTopTypename(@me)";
$z[10]=Array("field","",1034,1063);
$z[10][4]['name']="position";
$z[11]=Array("field","",1144,1203);
$z[11][4]['name']="typeid";
$z[11][4]['function']="GetTopTypename(@me)";
$z[12]=Array("channel","\r\n      <li>\r\n        <a href='[field:typeurl/]'>[field:typename/]</a>\r\n      </li>",1220,1417);
$z[12][4]['type']="son";
$z[12][4]['currentstyle']="<li class='hover'><a href='~typelink~'>~typename~</a></li>";
$z[13]=Array("field","",1498,1519);
$z[13][4]['name']="content";
$z[14]=Array("include","",4175,4212);
$z[14][4]['filename']="footer.htm";

?>