<?php
$z[0]=Array("field","",143,162);
$z[0][4]['name']="title";
$z[1]=Array("global","",163,189);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",230,259);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",299,357);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",375,407);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",491,523);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",609,644);
$z[6][4]['filename']="head.htm";
$z[7]=Array("global","",675,707);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("field","",715,774);
$z[8][4]['name']="typeid";
$z[8][4]['function']="GetTopTypename(@me)";
$z[9]=Array("field","",932,961);
$z[9][4]['name']="position";
$z[10]=Array("field","",1046,1105);
$z[10][4]['name']="typeid";
$z[10][4]['function']="GetTopTypename(@me)";
$z[11]=Array("channel","\r\n      <li>\r\n        <a href='[field:typeurl/]'>[field:typename/]</a>\r\n      </li>",1122,1319);
$z[11][4]['type']="son";
$z[11][4]['currentstyle']="<li class='hover'><a href='~typelink~'>~typename~</a></li>";
$z[12]=Array("list","\r\n      <li class=\"clearfix\"><span class=\"head\"><a href=\"[field:arcurl/]\">[field:title/]</a></span><span>[field:fundsize/]</span><span>[field:income/]</span><span>[field:deadline/]</span><span class=\"status\">[field:state/]</span></li>\r\n       ",2303,2583);
$z[12][4]['pagesize']="10";
$z[13]=Array("pagelist","",2608,2681);
$z[13][4]['listsize']="3";
$z[13][4]['listitem']="index pre pageno next end option";
$z[14]=Array("include","",2737,2774);
$z[14][4]['filename']="footer.htm";

?>